(define (make-button-state style layout #!optional description)
  `((style . ,(make-widget-model style))
    (layout . ,(make-widget-model layout))
    (description . ,(if (default-object? description) "" description))
    (disabled . #f)))

(define (make-button #!optional description)
  (let ((style (make-widget "ButtonStyleModel" "StyleView"))
        (layout (make-widget "LayoutModel" "LayoutView")))
    (let ((state (make-slider-state style layout)))
      (let ((widget (make-widget "ButtonModel" "ButtonView" state)))
        (display-widget widget)
        widget))))

(define set-button-description! (widget-updater 'description string?))
(define set-button-disabled! (widget-updater 'disabled boolean?))
