;; Contexts
(define zmq-context-options
  '((io-threads 1)
    (max-sockets 2)
    (socket-limit 3)
    (thread-priority 3)
    (thread-sched-policy 4)
    (max-msgsz 5)
    (msg-t-size 6)
    (thread-affinity-cpu-add 7)
    (thread-affinity-cpu-remove 8)
    (thread-name-prefix 9)))

;; Sockets
(define zmq-socket-types
  '((pair   0)
    (pub    1)
    (sub    2)
    (req    3)
    (rep    4)
    (dealer 5)
    (router 6)
    (pull   7)
    (push   8)
    (xpub   9)
    (xsub   10)
    (stream 11)))

(define zmq-socket-options
  '((affinity 4)
    (routing-id 5)
    (subscribe 6)
    (unsubscribe 7)
    (rate 8)
    (recovery-ivl 9)
    (sndbuf 11)
    (rcvbuf 12)
    (rcvmore 13)
    (fd 14)
    (events 15)
    (type 16)
    (linger 17)
    (reconnect-ivl 18)
    (backlog 19)
    (reconnect-ivl-max 21)
    (maxmsgsize 22)
    (sndhwm 23)
    (rcvhwm 24)
    (multicast-hops 25)
    (rcvtimeo 27)
    (sndtimeo 28)
    (last-endpoint 32)
    (router-mandatory 33)
    (tcp-keepalive 34)
    (tcp-keepalive-cnt 35)
    (tcp-keepalive-idle 36)
    (tcp-keepalive-intvl 37)
    (immediate 39)
    (xpub-verbose 40)
    (router-raw 41)
    (ipv6 42)
    (mechanism 43)
    (plain-server 44)
    (plain-username 45)
    (plain-password 46)
    (curve-server 47)
    (curve-publickey 48)
    (curve-secretkey 49)
    (curve-serverkey 50)
    (probe-router 51)
    (req-correlate 52)
    (req-relaxed 53)
    (conflate 54)
    (zap-domain 55)
    (router-handover 56)
    (tos 57)
    (connect-routing-id 61)
    (gssapi-server 62)
    (gssapi-principal 63)
    (gssapi-service-principal 64)
    (gssapi-plaintext 65)
    (handshake-ivl 66)
    (socks-proxy 68)
    (xpub-nodrop 69)
    (blocky 70)
    (xpub-manual 71)
    (xpub-welcome-msg 72)
    (stream-notify 73)
    (invert-matching 74)
    (heartbeat-ivl 75)
    (heartbeat-ttl 76)
    (heartbeat-timeout 77)
    (xpub-verboser 78)
    (connect-timeout 79)
    (tcp-maxrt 80)
    (thread-safe 81)
    (multicast-maxtpdu 84)
    (vmci-buffer-size 85)
    (vmci-buffer-min-size 86)
    (vmci-buffer-max-size 87)
    (vmci-connect-timeout 88)
    (use-fd 89)
    (gssapi-principal-nametype 90)
    (gssapi-service-principal-nametype 91)
		(bindtodevice 92)))

;; Poll Event Types
(define zmq-poll-events
	'((pollin 1)
		(pollout 2)
		(pollerr 4)
		(pollpri 8)))
		
;; Messages
(define zmq-message-options
  '((more 1)
    (srcfd 2)
		(shared 3)))

(export-to
	zmq-context-options
	zmq-socket-types
	zmq-socket-options
	zmq-poll-events
	zmq-message-options)