(define (slider-state style layout)
  `((max . 100)
    (style . ,(make-widget-model style))
    (layout . ,(make-widget-model layout))
    (_dom_classes . #())
    (orientation . "horizontal")
    (continuous_update . #t)
    (step . 1)
    (readout_format . "d")
    (readout . #t)
    (disabled . #f)
    (value . #f)))

(define (make-slider)
  (let ((style (make-widget "SliderStyleModel" "StyleView"))
        (layout (make-widget "LayoutModel" "LayoutView")))
    (let ((state (slider-state style layout)))
      (let ((widget (make-widget "IntSliderModel" "IntSliderView" state)))
        (display-widget widget)
        widget))))