(define (make-text-state layout)
  `((value . 0)
    (min . 0)
    (max . 100)
    (step . 1)
    (disabled . #f)
    (layout . ,(make-widget-model layout))
    (_dom_classes . #())
    (continuous_update . #t)))

(define (make-text)
  (let ((layout (make-widget "LayoutModel" "LayoutView")))
    (let ((state (make-text-state layout)))
      (let ((widget (make-widget "IntTextModel" "IntTextView")))
        (display-widget widget)
        widget))))

(define set-text-value! (widget-updater 'value integer?))
(define set-text-min! (widget-updater 'min integer?))
(define set-text-max! (widget-updater 'max integer?))
(define set-text-step! (widget-updater 'step integer?))
(define set-text-disabled! (widget-updater 'disabled boolean?))
